from .misc import get_terminal_size

GAME_SIZE = get_terminal_size()
FPS = 120


SPEED_INCREMENT = 1
SPEED_DECREMENT = -1
BASE_SPEED = 5
MAX_SPEED = 99
SPEED_STICKY_TIME = 0.2
STEERING_STICKY_TIME = 0.5
STEERING_STEP = 0.06


HORIZON = 0.5  
TRACK_SLOPE = 0.7  
DEBRIS_SPEED_MULTIPLIER = 1.0
MAX_NUM_DEBRIS = 20


MAX_NUM_CARS = 4
